name 'dhoppe-icinga'
version '0.0.6'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-icinga'
source 'git://github.com/dhoppe/puppet-icinga'
summary 'Icinga Module'
description 'Icinga Module for Debian, Ubuntu'
dependency 'dhoppe/role', '>=0.0.1'
dependency 'dhoppe/sudo', '>=0.0.1'
